language: node_js
node_js:
  - 0.8
before_install:
  - sudo apt-get update -qq
  - sugo apt-get install -qq make gcc libssl-dev cmake libsrtp0-dev libsrtp0 libnice10 libnice-dev libglib2.0-dev pkg-config libboost-regex-dev libboost-thread-dev libboost-system-dev
branches:
  only: travis-test