language: node_js
node_js:
  - 0.8
before_install:
  - ./.travis/scripts/install_chrome.sh
  - sudo apt-get install -qq make gcc libssl-dev cmake libsrtp0-dev libsrtp0 libnice10 libnice-dev libglib2.0-dev pkg-config libboost-regex-dev libboost-thread-dev libboost-system-dev
  - ./scripts/installErizo.sh
  - ./scripts/installNuve.sh
  - ./scripts/installBasicExample.sh
  - ./scripts/initLynckia.sh
  - sleep 10
  - ./scripts/initBasicExample.sh
branches:
  only: travis-test