markdown: rdiscount
permalink: licode/:title.html
destination: ./site/
auto: true
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
baseurl: /
domain: lynckia.com
title: Licode - Open Source Communication Provider
server: true
author: Lynckia
web: http://www.lynckia.com
twitter: lynckia
github: ging/lynckia
feedburner: 
  id: lynckia